services:

  tracker:

    build: ./tracker
    volumes:
      - ./database:/data
    expose:
      - "5000"
    env_file:
      - ./.env

  nginx:

    build: ./nginx
    ports:
      - "8084:80"
    depends_on:
      - tracker

  mailservice:

    build: ./mailservice
    volumes:
      - ./database:/data
    profiles:
      - tools
    env_file:
      - ./.env
